name: marching-squares
version: 0.1.0.0
author: フズキ

description: Marching squares algorithm implementation

dependencies:
- base >= 4.7 && < 5
- gloss
- array

executables:
  marching-squares:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
